export const words = [
  'cielo', 'gato', 'sol', 'tren', 'luna', 'verde', 'flor',
  'río', 'nube', 'mar', 'fuego', 'campo', 'piedra', 'frío',
  'arena', 'perro', 'café', 'rojo', 'roca', 'nieve', 'casa',
  'bosque', 'viento', 'canción', 'montaña', 'rayo', 'laguna',
  'estrella', 'libro', 'noche', 'puente', 'jardín', 'hoja',
  'rastro', 'silencio', 'camino', 'risa', 'tarde', 'barco',
  'sal', 'lago', 'metal', 'lluvia', 'oro', 'hierro', 'cuerda',
  'pluma', 'palma', 'caracol', 'pájaro', 'madera', 'vela',
  'cuerda', 'puerta', 'piedra', 'humo', 'árbol', 'llama',
  'faro', 'pan', 'vino', 'aceite', 'gota', 'arena', 'marea',
  'brisa', 'nido', 'puerto', 'isla', 'cosecha', 'mundo',
  'llanura', 'pescador', 'nave', 'tormenta', 'orilla', 'acero',
  'acantilado', 'flamenco', 'cascada', 'guitarra', 'ladrillo',
  'mirada', 'trigo', 'sombra', 'luz', 'fresco', 'cobre',
  'alba', 'crepúsculo', 'poema', 'canto', 'espiga', 'colina',
  'campana', 'lucero', 'techo', 'pared', 'sabana', 'valle',
  'astro', 'muralla', 'parque', 'puñado', 'finca', 'molino',
  'charco', 'río', 'avenida', 'lienzo', 'cántaro', 'farol',
  'ancla', 'zafiro', 'pasto', 'coral', 'marfil', 'loto',
  'sierra', 'florero', 'barro', 'arena', 'ladera', 'bisagra',
  'horizonte', 'planicie', 'huerto', 'melodía'
];